/**
 * GeoJSON `country_name` / `country_ship` values → ISO 3166-1 alpha-2 for flagcdn.
 * Base map aligned with oceanops-data-exports/geoCountryNames.mjs; extras cover ship registries.
 */
const GEO_COUNTRY_ISO: Record<string, string> = {
  ARGENTINA: 'AR',
  AUSTRALIA: 'AU',
  BAHAMAS: 'BS',
  BANGLADESH: 'BD',
  BELGIUM: 'BE',
  BERMUDA: 'BM',
  BRAZIL: 'BR',
  BULGARIA: 'BG',
  CANADA: 'CA',
  CHILE: 'CL',
  CHINA: 'CN',
  COLOMBIA: 'CO',
  'COOK ISLANDS': 'CK',
  CROATIA: 'HR',
  CUBA: 'CU',
  DENMARK: 'DK',
  EUMETNET: 'EU',
  EUROPE: 'EU',
  FINLAND: 'FI',
  FRANCE: 'FR',
  GERMANY: 'DE',
  GREECE: 'GR',
  'HONG KONG': 'HK',
  ICELAND: 'IS',
  INDIA: 'IN',
  INDONESIA: 'ID',
  IRELAND: 'IE',
  ISRAEL: 'IL',
  ITALY: 'IT',
  JAPAN: 'JP',
  JORDAN: 'JO',
  KIRIBATI: 'KI',
  'MARSHALL IS.': 'MH',
  MAURITIUS: 'MU',
  MEXICO: 'MX',
  MICRONESIA: 'FM',
  NAURU: 'NR',
  NETHERLANDS: 'NL',
  'NEW ZEALAND': 'NZ',
  NORWAY: 'NO',
  PANAMA: 'PA',
  PNG: 'PG',
  PERU: 'PE',
  PHILIPPINES: 'PH',
  POLAND: 'PL',
  PORTUGAL: 'PT',
  'PUERTO RICO': 'PR',
  RUSSIA: 'RU',
  SINGAPORE: 'SG',
  SLOVENIA: 'SI',
  'SOUTH AFRICA': 'ZA',
  'SOUTH KOREA': 'KR',
  SPAIN: 'ES',
  SWEDEN: 'SE',
  THAILAND: 'TH',
  TONGA: 'TO',
  TUVALU: 'TV',
  UAE: 'AE',
  UK: 'GB',
  UKRAINE: 'UA',
  UN: 'UN',
  USA: 'US',
  URUGUAY: 'UY',
  VANUATU: 'VU',
  'VIET NAM': 'VN',
  'WALLIS/FUTUNA': 'WF',
  // Ship registries and territories (not in partner ISO export)
  ANTARCTICA: 'AQ',
  'ANTIGUA&BARBUDA': 'AG',
  BARBADOS: 'BB',
  BRUNEI: 'BN',
  'CAPE VERDE': 'CV',
  'CAYMAN ISLANDS': 'KY',
  'COSTA RICA': 'CR',
  CYPRUS: 'CY',
  'FALKLAND IS.': 'FK',
  'FAROE IS.': 'FO',
  FIJI: 'FJ',
  'FR. POLYNESIA': 'PF',
  'FRANCE/METROP.': 'FR',
  GHANA: 'GH',
  GIBRALTAR: 'GI',
  GREENLAND: 'GL',
  'GUINEA-BISSAU': 'GW',
  HONDURAS: 'HN',
  ISLAND_OF_MAN: 'IM',
  JAMAICA: 'JM',
  LIBERIA: 'LR',
  MALTA: 'MT',
  'NEW CALEDONIA': 'NC',
  'NORFOLK ISLAND': 'NF',
  PALAU: 'PW',
  REUNION: 'RE',
  ROMANIA: 'RO',
  SAMOA: 'WS',
  SEYCHELLES: 'SC',
  'SOLOMON ISLANDS': 'SB',
  'ST. VINCENT&GR.': 'VC',
  SWITZERLAND: 'CH',
  TANZANIA: 'TZ',
  TUNISIA: 'TN',
  'VIRGIN IS.(USA)': 'VI',
}

export function getGeoCountryCode(name: string): string | undefined {
  const key = name.trim().toUpperCase()
  if (!key || key === 'UNKNOWN') return undefined
  return GEO_COUNTRY_ISO[key]
}
