/**
 * Edition headline stats — AUTO-GENERATED by oceanops-data-exports/export-observations-per-day.mjs
 * Regenerate: npm run export:observations (from oceanops-data-exports or oceanops-report-card)
 *
 * Source: observations-export/queries.mjs (source hierarchy, rolling average)
 * Last updated: 2026-08-18
 */

/** Rolling average of ocean observations per day (source hierarchy). */
export const OBSERVATIONS_PER_DAY_AVG = 105437

/** Rolling window in days (edition.values.json → OBS_DAYS_WINDOW). */
export const OBSERVATIONS_DAYS_WINDOW = 240

/** Days with at least one observation in the window. */
export const OBSERVATIONS_DAYS_WITH_DATA = 241

/** Total observations in the window. */
export const OBSERVATIONS_TOTAL = 25410384
