/**
 * Partner Countries Data
 *
 * AUTO-GENERATED by scripts/export-partner-countries.mjs — do not edit counts by hand.
 * Regenerate: npm run export:partners
 *
 * Data source: OceanOPS operational platform metadata (program country attribution)
 * Last updated: 2026-07-08
 *
 * Note: goShip can be:
 * - A number (0 or positive): actual platform count
 * - -1: represents "X" (participates but count not tracked)
 */

interface CountryNetworks {
  driftingBuoys: number
  argo: number
  oceanGliders: number
  aniBOS: number
  fvon: number
  sotVos: number
  sotAsap: number
  sot: number
  goShip: number // -1 represents "X" (participates but not counted)
  gloss: number
  oceanSites: number
  mooredBuoys: number
  tsunamiBuoys: number
  hfRadars: number
}

export interface PartnerCountry {
  name: string
  countryCode?: string // ISO 3166-1 alpha-2 code for flag display
  description?: string // Optional description specific to this country
  networks: CountryNetworks
}

export const partnerCountries: PartnerCountry[] = [
  {
    name: "AQ",
    countryCode: "AQ",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Argentina",
    countryCode: "AR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 4, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Australia",
    countryCode: "AU",
    networks: { driftingBuoys: 49, argo: 288, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 26, sotAsap: 0, sot: 4, goShip: 0, gloss: 15, oceanSites: 0, mooredBuoys: 35, tsunamiBuoys: 0, hfRadars: 12 }
  },
  {
    name: "Bermuda",
    countryCode: "BM",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Brazil",
    countryCode: "BR",
    networks: { driftingBuoys: 0, argo: 11, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Bulgaria",
    countryCode: "BG",
    networks: { driftingBuoys: 0, argo: 7, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Canada",
    countryCode: "CA",
    networks: { driftingBuoys: 21, argo: 207, oceanGliders: 3, aniBOS: 0, fvon: 0, sotVos: 36, sotAsap: 0, sot: 0, goShip: 0, gloss: 5, oceanSites: 0, mooredBuoys: 32, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Chile",
    countryCode: "CL",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 5, oceanSites: 0, mooredBuoys: 2, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "China",
    countryCode: "CN",
    networks: { driftingBuoys: 0, argo: 78, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 69, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 3, mooredBuoys: 3, tsunamiBuoys: 0, hfRadars: 19 }
  },
  {
    name: "Colombia",
    countryCode: "CO",
    networks: { driftingBuoys: 0, argo: 1, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Cook Islands",
    countryCode: "CK",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Croatia",
    countryCode: "HR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Cuba",
    countryCode: "CU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Denmark",
    countryCode: "DK",
    networks: { driftingBuoys: 0, argo: 8, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "EN",
    countryCode: "EN",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 12, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "European Union",
    countryCode: "EU",
    description: "Platforms operated by Euro-Argo ERIC, EMSO ERIC, EUMETNET, EUMETSAT.",
    networks: { driftingBuoys: 95, argo: 29, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Finland",
    countryCode: "FI",
    networks: { driftingBuoys: 0, argo: 2, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "FJ",
    countryCode: "FJ",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "France",
    countryCode: "FR",
    networks: { driftingBuoys: 0, argo: 296, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 52, sotAsap: 0, sot: 14, goShip: 0, gloss: 12, oceanSites: 1, mooredBuoys: 33, tsunamiBuoys: 0, hfRadars: 9 }
  },
  {
    name: "Germany",
    countryCode: "DE",
    networks: { driftingBuoys: 11, argo: 297, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 352, sotAsap: 1, sot: 0, goShip: 0, gloss: 1, oceanSites: 2, mooredBuoys: 7, tsunamiBuoys: 0, hfRadars: 3 }
  },
  {
    name: "Greece",
    countryCode: "GR",
    networks: { driftingBuoys: 0, argo: 6, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "HK",
    countryCode: "HK",
    networks: { driftingBuoys: 1, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Iceland",
    countryCode: "IS",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "India",
    countryCode: "IN",
    networks: { driftingBuoys: 3, argo: 58, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 5, oceanSites: 1, mooredBuoys: 13, tsunamiBuoys: 0, hfRadars: 10 }
  },
  {
    name: "Indonesia",
    countryCode: "ID",
    networks: { driftingBuoys: 1, argo: 1, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Ireland",
    countryCode: "IE",
    networks: { driftingBuoys: 0, argo: 11, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 4, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "Israel",
    countryCode: "IL",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 3 }
  },
  {
    name: "Italy",
    countryCode: "IT",
    networks: { driftingBuoys: 4, argo: 100, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 1, mooredBuoys: 1, tsunamiBuoys: 0, hfRadars: 21 }
  },
  {
    name: "Japan",
    countryCode: "JP",
    networks: { driftingBuoys: 1, argo: 140, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 154, sotAsap: 0, sot: 1, goShip: 0, gloss: 14, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 22 }
  },
  {
    name: "Jordan",
    countryCode: "JO",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Kiribati",
    countryCode: "KI",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Korea (Republic Of)",
    countryCode: "KR",
    networks: { driftingBuoys: 8, argo: 18, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 18, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 34, tsunamiBuoys: 0, hfRadars: 25 }
  },
  {
    name: "Malta",
    countryCode: "MT",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "Marshall Islands",
    countryCode: "MH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Mauritius",
    countryCode: "MU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Mexico",
    countryCode: "MX",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Micronesia, Federated States Of",
    countryCode: "FM",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Nauru",
    countryCode: "NR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Netherlands",
    countryCode: "NL",
    networks: { driftingBuoys: 0, argo: 28, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 11, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "New Zealand",
    countryCode: "NZ",
    networks: { driftingBuoys: 2, argo: 16, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Norway",
    countryCode: "NO",
    networks: { driftingBuoys: 0, argo: 32, oceanGliders: 1, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 6, oceanSites: 1, mooredBuoys: 1, tsunamiBuoys: 0, hfRadars: 8 }
  },
  {
    name: "Papua New Guinea",
    countryCode: "PG",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Philippines",
    countryCode: "PH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Poland",
    countryCode: "PL",
    networks: { driftingBuoys: 0, argo: 10, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Portugal",
    countryCode: "PT",
    networks: { driftingBuoys: 0, argo: 4, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 3, tsunamiBuoys: 0, hfRadars: 10 }
  },
  {
    name: "Puerto Rico",
    countryCode: "PR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Russian Federation",
    countryCode: "RU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 8, sotAsap: 0, sot: 0, goShip: 0, gloss: 4, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Singapore",
    countryCode: "SG",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Slovenia",
    countryCode: "SI",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "South Africa",
    countryCode: "ZA",
    networks: { driftingBuoys: 0, argo: 2, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Spain",
    countryCode: "ES",
    networks: { driftingBuoys: 0, argo: 35, oceanGliders: 1, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 1, mooredBuoys: 16, tsunamiBuoys: 0, hfRadars: 30 }
  },
  {
    name: "Sweden",
    countryCode: "SE",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Thailand",
    countryCode: "TH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 1, tsunamiBuoys: 0, hfRadars: 6 }
  },
  {
    name: "Tonga",
    countryCode: "TO",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Tuvalu",
    countryCode: "TV",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "U-",
    countryCode: "U-",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 3, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Ukraine",
    countryCode: "UA",
    networks: { driftingBuoys: 0, argo: 6, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "UN",
    countryCode: "UN",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "United Arab Emirates",
    countryCode: "AE",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "United Kingdom",
    countryCode: "GB",
    networks: { driftingBuoys: 0, argo: 139, oceanGliders: 0, aniBOS: 19, fvon: 0, sotVos: 178, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 10, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "United States",
    countryCode: "US",
    networks: { driftingBuoys: 303, argo: 2498, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 599, sotAsap: 0, sot: 1, goShip: 0, gloss: 24, oceanSites: 59, mooredBuoys: 243, tsunamiBuoys: 0, hfRadars: 118 }
  },
  {
    name: "Uruguay",
    countryCode: "UY",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Vanuatu",
    countryCode: "VU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Viet Nam",
    countryCode: "VN",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 3 }
  },
  {
    name: "Wallis And Futuna Islands",
    countryCode: "WF",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  }
]
