/**
 * Partner Countries Data
 *
 * AUTO-GENERATED by oceanops-data-exports/export-partner-countries.mjs — do not edit counts by hand.
 * Regenerate: npm run export:partners (from oceanops-data-exports or oceanops-report-card)
 *
 * Data source: OceanOPS PostgreSQL (ptf_loc_n + cruise_program for lines), filters in sql/*.sql
 * Last updated: 2026-08-31
 *
 * Note: goShip can be:
 * - A number (0 or positive): GO-SHIP edition cruise count for the country (lead program country)
 * - -1: represents "X" (participates but count not tracked)
 */

interface CountryNetworks {
  driftingBuoys: number
  argo: number
  oceanGliders: number
  aniBOS: number
  fvon: number
  sotVos: number
  sotAsap: number
  sot: number
  goShip: number // -1 represents "X" (participates but not counted)
  gloss: number
  oceanSites: number
  mooredBuoys: number
  tsunamiBuoys: number
  hfRadars: number
}

export interface PartnerCountry {
  name: string
  countryCode?: string // ISO 3166-1 alpha-2 code for flag display
  description?: string // Optional description specific to this country
  networks: CountryNetworks
}

export const partnerCountries: PartnerCountry[] = [
  {
    name: "Argentina",
    countryCode: "AR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 4, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Australia",
    countryCode: "AU",
    networks: { driftingBuoys: 48, argo: 285, oceanGliders: 15, aniBOS: 33, fvon: 167, sotVos: 27, sotAsap: 0, sot: 0, goShip: 0, gloss: 15, oceanSites: 2, mooredBuoys: 30, tsunamiBuoys: 4, hfRadars: 12 }
  },
  {
    name: "Bahamas",
    countryCode: "BS",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 8, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Bermuda",
    countryCode: "BM",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Brazil",
    countryCode: "BR",
    networks: { driftingBuoys: 0, argo: 11, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 1, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Bulgaria",
    countryCode: "BG",
    networks: { driftingBuoys: 0, argo: 9, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Canada",
    countryCode: "CA",
    networks: { driftingBuoys: 36, argo: 204, oceanGliders: 23, aniBOS: 0, fvon: 0, sotVos: 36, sotAsap: 0, sot: 0, goShip: 2, gloss: 5, oceanSites: 5, mooredBuoys: 34, tsunamiBuoys: 0, hfRadars: 13 }
  },
  {
    name: "Chile",
    countryCode: "CL",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 6, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 5, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 2, hfRadars: 0 }
  },
  {
    name: "China",
    countryCode: "CN",
    networks: { driftingBuoys: 3, argo: 77, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 65, sotAsap: 0, sot: 0, goShip: 0, gloss: 4, oceanSites: 7, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 19 }
  },
  {
    name: "Colombia",
    countryCode: "CO",
    networks: { driftingBuoys: 0, argo: 1, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Cook Islands",
    countryCode: "CK",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Croatia",
    countryCode: "HR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 6 }
  },
  {
    name: "Cuba",
    countryCode: "CU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Denmark",
    countryCode: "DK",
    networks: { driftingBuoys: 0, argo: 8, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 4, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "European Union",
    countryCode: "EU",
    description: "Platforms operated by Euro-Argo ERIC, EMSO ERIC, EUMETNET, EUMETSAT.",
    networks: { driftingBuoys: 136, argo: 27, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 12, sot: 0, goShip: 0, gloss: 0, oceanSites: 2, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Finland",
    countryCode: "FI",
    networks: { driftingBuoys: 0, argo: 4, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "FJ",
    countryCode: "FJ",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 26, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "FO",
    countryCode: "FO",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 13, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "France",
    countryCode: "FR",
    networks: { driftingBuoys: 1, argo: 305, oceanGliders: 17, aniBOS: 1, fvon: 0, sotVos: 52, sotAsap: 0, sot: 0, goShip: 1, gloss: 12, oceanSites: 6, mooredBuoys: 33, tsunamiBuoys: 0, hfRadars: 9 }
  },
  {
    name: "Germany",
    countryCode: "DE",
    networks: { driftingBuoys: 10, argo: 280, oceanGliders: 3, aniBOS: 0, fvon: 0, sotVos: 363, sotAsap: 1, sot: 0, goShip: 2, gloss: 1, oceanSites: 43, mooredBuoys: 7, tsunamiBuoys: 0, hfRadars: 3 }
  },
  {
    name: "Greece",
    countryCode: "GR",
    networks: { driftingBuoys: 0, argo: 6, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 1, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "GW",
    countryCode: "GW",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 1, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Iceland",
    countryCode: "IS",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 10, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 1, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "India",
    countryCode: "IN",
    networks: { driftingBuoys: 6, argo: 113, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 5, oceanSites: 12, mooredBuoys: 10, tsunamiBuoys: 0, hfRadars: 10 }
  },
  {
    name: "Indonesia",
    countryCode: "ID",
    networks: { driftingBuoys: 0, argo: 1, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Ireland",
    countryCode: "IE",
    networks: { driftingBuoys: 0, argo: 10, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 4, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "Israel",
    countryCode: "IL",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "Italy",
    countryCode: "IT",
    networks: { driftingBuoys: 32, argo: 95, oceanGliders: 1, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 2, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 27 }
  },
  {
    name: "Japan",
    countryCode: "JP",
    networks: { driftingBuoys: 19, argo: 145, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 147, sotAsap: 1, sot: 0, goShip: 5, gloss: 14, oceanSites: 5, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 22 }
  },
  {
    name: "Jordan",
    countryCode: "JO",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Kiribati",
    countryCode: "KI",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Korea (Republic Of)",
    countryCode: "KR",
    networks: { driftingBuoys: 14, argo: 18, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 18, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 27, mooredBuoys: 34, tsunamiBuoys: 0, hfRadars: 25 }
  },
  {
    name: "Malta",
    countryCode: "MT",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "Marshall Islands",
    countryCode: "MH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Mauritius",
    countryCode: "MU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Mexico",
    countryCode: "MX",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Micronesia (Federated States Of)",
    countryCode: "FM",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Nauru",
    countryCode: "NR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Netherlands",
    countryCode: "NL",
    networks: { driftingBuoys: 0, argo: 26, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 9, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 8, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "New Zealand",
    countryCode: "NZ",
    networks: { driftingBuoys: 2, argo: 16, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Norway",
    countryCode: "NO",
    networks: { driftingBuoys: 0, argo: 38, oceanGliders: 2, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 1, gloss: 6, oceanSites: 5, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 8 }
  },
  {
    name: "Papua New Guinea",
    countryCode: "PG",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Peru",
    countryCode: "PE",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 2, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Philippines",
    countryCode: "PH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 3, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Poland",
    countryCode: "PL",
    networks: { driftingBuoys: 0, argo: 10, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Portugal",
    countryCode: "PT",
    networks: { driftingBuoys: 0, argo: 4, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 3, tsunamiBuoys: 0, hfRadars: 10 }
  },
  {
    name: "Puerto Rico",
    countryCode: "PR",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Russian Federation",
    countryCode: "RU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 9, sotAsap: 0, sot: 0, goShip: 0, gloss: 4, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 1 }
  },
  {
    name: "Singapore",
    countryCode: "SG",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Slovenia",
    countryCode: "SI",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "South Africa",
    countryCode: "ZA",
    networks: { driftingBuoys: 0, argo: 4, oceanGliders: 1, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Spain",
    countryCode: "ES",
    networks: { driftingBuoys: 0, argo: 38, oceanGliders: 5, aniBOS: 0, fvon: 0, sotVos: 2, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 2, mooredBuoys: 15, tsunamiBuoys: 0, hfRadars: 32 }
  },
  {
    name: "Sweden",
    countryCode: "SE",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 25, aniBOS: 0, fvon: 0, sotVos: 4, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "Thailand",
    countryCode: "TH",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 2, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 6 }
  },
  {
    name: "Tonga",
    countryCode: "TO",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Tuvalu",
    countryCode: "TV",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "TZ",
    countryCode: "TZ",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 25, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Ukraine",
    countryCode: "UA",
    networks: { driftingBuoys: 0, argo: 6, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "United Arab Emirates",
    countryCode: "AE",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 2 }
  },
  {
    name: "United Kingdom",
    countryCode: "GB",
    networks: { driftingBuoys: 0, argo: 139, oceanGliders: 13, aniBOS: 14, fvon: 10, sotVos: 181, sotAsap: 0, sot: 0, goShip: 3, gloss: 3, oceanSites: 41, mooredBuoys: 76, tsunamiBuoys: 0, hfRadars: 4 }
  },
  {
    name: "United States",
    countryCode: "US",
    networks: { driftingBuoys: 1009, argo: 2475, oceanGliders: 62, aniBOS: 0, fvon: 210, sotVos: 604, sotAsap: 0, sot: 0, goShip: 3, gloss: 24, oceanSites: 180, mooredBuoys: 202, tsunamiBuoys: 31, hfRadars: 172 }
  },
  {
    name: "Uruguay",
    countryCode: "UY",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Vanuatu",
    countryCode: "VU",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 1, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  },
  {
    name: "Viet Nam",
    countryCode: "VN",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 0, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 3 }
  },
  {
    name: "Wallis And Futuna Islands",
    countryCode: "WF",
    networks: { driftingBuoys: 0, argo: 0, oceanGliders: 0, aniBOS: 0, fvon: 0, sotVos: 0, sotAsap: 0, sot: 0, goShip: 0, gloss: 1, oceanSites: 0, mooredBuoys: 0, tsunamiBuoys: 0, hfRadars: 0 }
  }
]

/** Globe/report filter countries (rollup + whitelist). Matches simple-map getFilterableCountryNames. */
export const CONTRIBUTING_COUNTRIES = 65
